import { Syne } from "next/font/google";
import "./globals.css";

export const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-dvh ${syne.variable} antialiased`}>{children}</body>
    </html>
  );
}
